version: '3'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db_guo_inagaki_2017
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/guo-inagaki-2017
      - ./data:/data
    links:
      - db_guo_inagaki_2017
    ports:
      - "8891:8888"
  db_guo_inagaki_2017:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "4306:3306"
